[build]
  command = "npm run build"
  publish = "_site"

# Anda mungkin tidak memerlukan redirect sama sekali.
# Coba hapus semua aturan di bawah ini terlebih dahulu.
# Jika Anda benar-benar membutuhkannya (misalnya untuk Netlify CMS),
# versi yang benar adalah seperti ini (tanpa "/_site"):

# [[redirects]]
#   from = "/images/uploads/*"
#   to = "/images/uploads/:splat"
#   status = 200