[build]
  command = "npm run build"
  publish = "."

# === Redirection for blog subpath ===
[[redirects]]
  from = "/blog/*"
  to = "/blog/_site/:splat"
  status = 200

[[redirects]]
  from = "/blog"
  to = "/blog/"
  status = 301

[[redirects]]
  from = "/blog/*"
  to = "/blog/_site/:splat"
  status = 200
