[build]
  command = "npm run build"
  publish = "."

# Redirect agar semua /blog/* diarahkan ke hasil build Eleventy
[[redirects]]
  from = "/blog/*"
  to = "/_site/blog/:splat"
  status = 200

# Redirect agar semua /posts/... diarahkan ke hasil build blog
[[redirects]]
  from = "/posts/*"
  to = "/blog/_site/posts/:splat"
  status = 200

# Redirect agar gambar bisa diakses langsung
[[redirects]]
  from = "/images/uploads/*"
  to = "/blog/images/uploads/:splat"
  status = 200
