backend:
  name: git-gateway
  branch: master
  site_domain: kianolandgroup.com
  publish_mode: editorial_workflow
  # tambahkan ini:
  base_url: https://api.netlify.com
  auth_endpoint: /.netlify/functions/auth
  webhook_url: https://api.netlify.com/build_hooks/68e77b4e55d115bd755ed8cf

media_folder: "blog/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Berita"
    folder: "blog/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Tanggal", name: "date", widget: "datetime" }
      - { label: "Deskripsi Singkat", name: "summary", widget: "text" }
      - { label: "Gambar Utama", name: "thumbnail", widget: "image" }
      - { label: "Isi Artikel", name: "body", widget: "markdown" }
      - {
          label: "Tags",
          name: "tags",
          widget: "list",
          default: ["blog"],
          hidden: true,
        }
