backend:
  name: git-gateway
  branch: master

media_folder: "blog/images/uploads",
public_folder: "/blog/images/uploads",

collections:
  - name: "posts"
    label: "Berita"
    folder: "blog/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Tanggal", name: "date", widget: "datetime" }
      - { label: "Deskripsi Singkat", name: "summary", widget: "text" }
      - { label: "Gambar Utama", name: "thumbnail", widget: "image" }
      - { label: "Isi Artikel", name: "body", widget: "markdown" }
