backend:
  name: git-gateway
  branch: master

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts" # ✅ Koleksi untuk berita
    label: "Berita"
    folder: "blog/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Judul", name: "title", widget: "string" }
      - { label: "Tanggal", name: "date", widget: "datetime" }
      - { label: "Deskripsi Singkat", name: "summary", widget: "text" }
      - { label: "Gambar Utama", name: "thumbnail", widget: "image" }
      - { label: "Isi Artikel", name: "body", widget: "markdown" }

  - name: "pages" # ✅ Koleksi untuk halaman statis
    label: "Halaman Statis"
    folder: "pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Judul Halaman", name: "title", widget: "string" }
      - { label: "Konten", name: "body", widget: "markdown" }
